### ISSUE TITLE
Could you please help with a step by step installation process?

### ISSUE THREAD

**Issue by Ananasa** [agragregra/OctoberCMS-Gulp-Starter#1]

**Comment by wdmcourses** [comment]
https://www.youtube.com/watch?v=KMVOS5DMhSc&t=1003s

**Comment by Ananasa** [comment]
Thanks so much will try that and let you know about the results.

**Comment by Ananasa** [comment]
@agragregra I have tried to follow along with the video but i didn't work. The installation is tedious!

**Comment by agragregra** [comment]
И что?

**Comment by Ananasa** [comment]
Thank you so much, i don't speak Russian. :)
